version: "3"
services:
  seatrips-server:
    build: backend/
    ports:
      - "3000:3000"
    depends_on:
      - seatrips-db
    container_name: seatrips-docker-server
  seatrips-client:
    build: frontend/
    ports:
      - "8080:8080"
    container_name: seatrips-docker-client
  seatrips-db:
    image: mongo:latest
    container_name: seatrips-docker-db