version: "3"
services:
  server:
    build: backend/
    ports:
      - "3000:3000"
    depends_on:
      - db
    container_name: docker-server
  client:
    build: frontend/
    ports:
      - "8080:8080"
    container_name: docker-client
  db:
    image: mongo:latest
    container_name: docker-db